### ISSUE TITLE
feature request, hide filenames

### ISSUE THREAD

**Issue by KoljaL** [DanniScript/r-icons#1]
This extension is a great idea.

And it the files in a svelte route have individual icons, the don't need their names anymore.

Is there a way to hide them and show the icons in a row?

**Comment by Rinconx64** [comment]
Oh I think I get the idea. Would look something like this?
![Frame 48](https://user-images.githubusercontent.com/25558870/228971126-441a59d1-ab42-45be-9466-b8c5162ec4ff.png)
